name: Release pip package

on:
  release:
    types: [released]
  pull_request: []

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.8
          uses: actions/setup-python@v1
          with:
            python-version: 3.8
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - --version 1.0.0
            echo "$HOME/.poetry/bin" >> $GITHUB_PATH

        - name: Build
          run: |
            poetry install
            make dist

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - --version 1.0.0
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Test
        run: |
          poetry install
          make test

  lint:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Set up Python 3.8
       uses: actions/setup-python@v1
       with:
         python-version: 3.8
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - --version 1.0.0
         echo "$HOME/.poetry/bin" >> $GITHUB_PATH

     - name: Lint
       run: |
         poetry install
         make lint

  publish:
    runs-on: ubuntu-latest
    needs: [build, test, lint]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.0
      - name: Publish
        run: poetry publish -u $PYPI_USERNAME -p $PYPI_PASSWORD --dry-run
        env:
          PYPI_USERNAME: "PYPI_USERNAME"
          PYPI_PASSWORD: "PYPI_PASSWORD"
#          PYPI_USERNAME: "${{ secrets.PYPI_USERNAME }}"
#          PYPI_PASSWORD: "${{ secrets.PYPI_PASSWORD }}"
